language: ruby
rvm:
- 2.3.0
script:
- rake db:migrate
- rake db:test:prepare
- rake db:test:prepare
- bundle exec rspec -fd spec/
rspec spec
after_success:
  - coveralls:report
notifications:
  email: false

