language: ruby
rvm:
- 2.3.0
script:
- bundle exec rake db:create
- bundle exec rake db:reset
- bundle exec rake db:migrate
- bundle exec rspec -fd spec
after_success:
  - coveralls
notifications:
  email: false

