language: ruby
rvm:
- 2.3.0
script:
- bundle exec rake db:create
- bundle exec rake db:migrate RAILS_ENV="development"
- bundle exec rspec -fd spec
after_success:
  - coveralls:report
notifications:
  email: false

