development:
  server: "http://omnistrimfaye.herokuapp.com/faye"
  secret_token: "omnistrim"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://omnistrimfaye.herokuapp.com/faye"
  secret_token: "omnistrim"
  signature_expiration: 7200
