# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef4bcda2746d4965d5ba8a5167d1c7cfaa1c7456b3feb596882184745974ebe2032d3b90bce8d75f8e3ede3432540808dcee673505d75b47ea26e34c0001e737

test:
  secret_key_base: 3f0875929deb29134d62455313365a9cee07bf60c335092ff59a8377b7f31f4a7eaa2528adcba56ce75e0ba203c2c07f3ddb72fd41bf5ea294b4f383dc97bc2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
