# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54ba38dfee662372da22627d364453d2f8b6365a8c3de2755f5012b42476f7577193173932f9043d7c40bccee88bb5c2a526a39de0284a9a1cf1522fbf9d81a0

test:
  secret_key_base: 6943aa2f22250aeaf606dda5f84f913d773d29209db1ded95973ac47393c0411e8a10cd9f8d02d9637ef47622892a5d4b050f3e6537c0a04fef63ab3940979be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
